language: python
branches:
  only:
  - content
install:
- pip install pelican ghp-import
script:
- make publish github
env:
  global:
    secure: LKuh8uSvKnD/d/hf9unIPX1TFIVf09yQLdP+cJcn3X7jiZkXAvzj4tDyLZPwQ342uVFBs3u3CkIp7RhLu/wn/z+eW/0xfo6poZjWQ5k4s+sNjN1XPK28mj+krBKkp8OSdMmJ4xLoSWxnV5V0fwDGJRxwLtUZnZYVx3OxZrc790Q=